import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp,
  ArrowUpRight,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Bug,
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsUp,
  Clapperboard,
  Code2,
  Copy,
  CornerDownLeft,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  File,
  FileCode2,
  FileText,
  Flag,
  Folder,
  Gamepad2,
  Gauge,
  GitFork,
  Globe2,
  Headphones,
  HelpCircle,
  History,
  Image,
  Info,
  KeyRound,
  LayoutGrid,
  Lightbulb,
  Link,
  Lock,
  Maximize2,
  MessageSquare,
  Mic,
  MonitorSmartphone,
  Moon,
  MoreVertical,
  Music,
  Orbit,
  Paintbrush,
  PanelLeftClose,
  Pencil,
  Plus,
  PlusCircle,
  Radio,
  RefreshCw,
  Rocket,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  ThumbsDown,
  ThumbsUp,
  TrendingDown,
  TrendingUp,
  UserCheck,
  Users,
  Video,
  Wand2,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

// The old implementation emitted Material ligature names into a subsetted icon
// font. Any name missing from that subset appeared as raw text. Keeping the
// familiar AI Studio names at call sites is convenient, but rendering is now
// SVG-only and unknown names get a safe icon instead of leaking a string.
const ICONS: Record<string, LucideIcon> = {
  add: Plus,
  add_circle: PlusCircle,
  antigravity: Orbit,
  arrow_back: ArrowLeft,
  arrow_outward: ArrowUpRight,
  arrow_split: GitFork,
  arrow_upward_alt: ArrowUp,
  attach_money: DollarSign,
  auto_stories: BookOpen,
  bedtime: Moon,
  bolt: Zap,
  book: BookOpen,
  bug_report: Bug,
  build: Wrench,
  calendar_today: Calendar,
  chat_bubble: MessageSquare,
  chat_spark: MessageSquare,
  check_circle: CheckCircle2,
  chevron_down: ChevronDown,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  close: X,
  code: Code2,
  collapse_all: ChevronsUp,
  compare_arrows: ArrowLeftRight,
  content_copy: Copy,
  data_object: Code2,
  description: FileText,
  developer_guide: BookOpen,
  devices: MonitorSmartphone,
  download: Download,
  draft: File,
  draw: Paintbrush,
  edit: Pencil,
  error: HelpCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  external_link: ExternalLink,
  eye: Eye,
  flag: Flag,
  folder: Folder,
  fullscreen: Maximize2,
  gallery_thumbnail: Image,
  gamepad: Gamepad2,
  google: Globe2,
  grid_view: LayoutGrid,
  group: Users,
  history: History,
  image: Image,
  image_edit_auto: Wand2,
  info: Info,
  key: KeyRound,
  key_off: KeyRound,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  keyboard_return: CornerDownLeft,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  menu_book: BookOpen,
  menu_open: PanelLeftClose,
  mic: Mic,
  moon: Moon,
  more_vert: MoreVertical,
  movie: Clapperboard,
  music_note: Music,
  network_intelligence_history: History,
  notifications: Bell,
  open_in_new: ArrowUpRight,
  people: Users,
  query_stats: BarChart3,
  radio: Radio,
  redo: RotateCcw,
  reset_settings: RotateCcw,
  rocket_launch: Rocket,
  search: Search,
  segment: FileCode2,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shield_check: ShieldCheck,
  smart_toy: Bot,
  smartphone: Smartphone,
  spark: Sparkles,
  speed: Gauge,
  sports_esports: Gamepad2,
  star: Star,
  stylus: Paintbrush,
  summarize: FileText,
  support_agent: Headphones,
  sync: RefreshCw,
  thumb_down: ThumbsDown,
  thumb_up: ThumbsUp,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  user_check: UserCheck,
  users: Users,
  video_camera_front: Video,
  video_spark: Video,
  view_module: LayoutGrid,
  visibility: Eye,
  widgets: LayoutGrid,
};

export function MsIcon({
  name,
  size = 18,
  className,
  style,
}: {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Icon = ICONS[name] ?? HelpCircle;

  return (
    <Icon
      aria-hidden
      className={`shrink-0 ${className ?? ""}`}
      size={size}
      strokeWidth={1.8}
      style={style}
    />
  );
}
